# Generated by Django 4.2 on 2025-04-15 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('mañana', 'Mañana (10:00 a 14:00)'), ('tarde', 'Tarde (13:00 a 19:00)')], max_length=10)),
                ('init_hour', models.TimeField()),
                ('end_hour', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id_reserve', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('date_reserve', models.DateField()),
                ('cuantity', models.IntegerField()),
                ('message', models.TextField(blank=True, null=True)),
                ('time_reserve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ship.schedules')),
            ],
        ),
    ]
