# Generated by Django 4.2 on 2025-04-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('section', models.CharField(choices=[('home', 'Inicio'), ('services', 'Servicios'), ('about', 'Nosotros'), ('gallery', 'Galería')], max_length=20)),
                ('image', models.ImageField(upload_to='images/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
