# Generated by Django 4.2 on 2025-05-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='section',
            field=models.CharField(choices=[('hero', 'Hero'), ('how-it-works', 'Hot it works'), ('carrousel', 'Carrusel'), ('reserve', 'Reserve')], max_length=20),
        ),
    ]
