# Generated by Django 4.2 on 2025-05-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0005_remove_image_image_image_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='section',
            field=models.CharField(choices=[('hero', 'hero'), ('how-it-works', 'how it works'), ('carrousel', 'carrusel'), ('reserve', 'reserve')], max_length=20),
        ),
    ]
