# Generated by Django 4.2 on 2025-05-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0007_auto_20250515_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='email',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='phone',
        ),
        migrations.AddField(
            model_name='reserve',
            name='contact',
            field=models.CharField(default='contacto', max_length=100, verbose_name='Email o Teléfono'),
            preserve_default=False,
        ),
    ]
