# Generated by Django 4.2 on 2025-05-19 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0008_remove_reserve_email_remove_reserve_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserve',
            old_name='date_reserve',
            new_name='date_selected',
        ),
        migrations.RenameField(
            model_name='reserve',
            old_name='cuantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='reserve',
            old_name='time_reserve',
            new_name='time_selected',
        ),
    ]
