# Generated by Django 4.2 on 2025-05-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0009_rename_date_reserve_reserve_date_selected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='type',
            field=models.CharField(choices=[('mañana', 'Mañana (8:00 a 12:00)'), ('mañana', 'Mañana (9:00 a 13:00)'), ('mañana', 'Mañana (10:00 a 14:00)'), ('tarde', 'Tarde (13:00 a 19:00)'), ('tarde', 'Tarde (14:00 a 20:00)'), ('tarde', 'Tarde (14:00 a 18:00)'), ('tarde', 'Tarde (15:00 a 19:00)'), ('tarde', 'Tarde (16:00 a 20:00)')], max_length=10),
        ),
    ]
