# Generated by Django 4.2 on 2025-05-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0011_alter_schedules_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='type',
            field=models.CharField(choices=[('mañana_1', 'Mañana (8:00 a 12:00)'), ('mañana_2', 'Mañana (9:00 a 13:00)'), ('mañana_3', 'Mañana (10:00 a 14:00)'), ('tarde_1', 'Tarde (13:00 a 19:00)'), ('tarde_2', 'Tarde (14:00 a 20:00)'), ('tarde_3', 'Tarde (14:00 a 18:00)'), ('tarde_4', 'Tarde (15:00 a 19:00)'), ('tarde_5', 'Tarde (16:00 a 20:00)')], max_length=10),
        ),
    ]
