# Generated by Django 4.2 on 2025-05-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0012_alter_schedules_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada')], default='pending', max_length=10),
        ),
    ]
