# Generated by Django 4.2 on 2025-05-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0013_reserve_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='method_payment',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta')], default='cash', max_length=10),
        ),
    ]
