# Generated by Django 4.2 on 2025-05-29 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0014_reserve_method_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='method_payment',
        ),
    ]
