# Generated by Django 4.2 on 2025-06-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0015_remove_reserve_method_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video_url', models.URLField()),
                ('section', models.CharField(choices=[('ship', 'ship')], max_length=20)),
            ],
        ),
    ]
